name: Python Script Pipeline

on:
  workflow_dispatch:
    
  push:
    branches:
      - master

permissions:
  contents: write
  actions: read

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:          
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      # - name: Build Application with Maven (Capture Logs)
      #   id: build_app
      #   run: |
      #     set +e
      #     echo "Running mvn clean package..."
      #     mvn clean package --batch-mode --no-transfer-progress > build_output.log 2>&1
      #     BUILD_STATUS=$?
      #     echo "::group::Maven Output (tail)"
      #     tail -n 50 build_output.log || echo "No output file"
      #     echo "::endgroup::"
      #     if [ $BUILD_STATUS -ne 0 ]; then
      #       echo "Build failed, capturing logs..."
      #       tail -n 50 build_output.log | tr '\n' ' ' | sed 's/"/\\"/g' > error.log
      #       ERROR_MSG=$(cat error.log)
      #       echo "error_message=$ERROR_MSG" >> "$GITHUB_OUTPUT"
      #     fi
      #     exit $BUILD_STATUS
      #   shell: bash

      # - name: Show Error Message Output
      #   if: failure()
      #   run: |
      #     echo "Captured Error Output:"
      #     echo "${{ steps.build_app.outputs.error_message }}" 

      # - name: Prepare Error Log for Deployment
      #   if: failure()
      #   run: |
      #     mkdir -p "${{ github.ref_name }}/${{ github.run_number }}"
      #     cp error.log "${{ github.ref_name }}/${{ github.run_number }}/error.log"

      # - name: Deploy to gh-pages
      #   if: failure()
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ${{ github.ref_name }}
      #     keep_files: true

      - name: Build Application with Maven
        run: mvn clean package --batch-mode --no-transfer-progress

      - name: Set up Python
        if: failure()
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # - name: Install Slack SDK
      #   if: failure()
      #   run: pip install slack-sdk

      - name: Install Requests
        if: failure()
        run: pip install requests

      - name: Run Pipeline Details Script
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: python .github/scripts/PipelineDetails.py --fetch-logs

      # - name: Run Slack Notifier 
      #   if: failure()
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      #     SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ID }}
      #     REPO: ${{ github.repository }}
      #     BRANCH: ${{ github.ref_name }}
      #     ACTOR: ${{ github.actor }}
      #     RUN_ID: ${{ github.run_id }}
      #     RUN_NUMBER: ${{ github.run_number }}
      #     GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      #   run: python .github/scripts/slack_notify.py PipelineDetails


  # Ping_FastAPI:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Ping FastAPI URL
  #       run: |
  #         echo "Pinging FastAPI Handler..."
  #         curl --silent https://fastapi-slack-handler.onrender.com || true