name: Teams-Buttons-Notifier

on:
  workflow_dispatch:
  push:
    branches:
      - pa-method

permissions:
  contents: write
  actions: read

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:          
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Build Application with Maven
        id: build_app
        run: |
          set +e
          mvn clean package --batch-mode --no-transfer-progress > build_output.log 2>&1
          BUILD_STATUS=$?
          if [ $BUILD_STATUS -ne 0 ]; then
            tail -n 50 build_output.log > error.log
          fi
          exit $BUILD_STATUS

      - name: Prepare Error Log for Deployment
        if: failure()
        run: |
          mkdir -p "${{ github.ref_name }}/${{ github.run_number }}"
          cp error.log "${{ github.ref_name }}/${{ github.run_number }}/error.log"

      - name: Deploy to gh-pages
        if: failure()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.ref_name }}
          keep_files: true

      - name: Set up Python
        if: failure()
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        if: failure()
        run: pip install requests

      - name: Run NEW Teams Buttons Notifier 
        if: failure()
        env:
          TEAMS_BUTTONS_WEBHOOK_URL: ${{ secrets.TEAMS_BUTTONS_WEBHOOK_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python .github/scripts/teams_notify_buttons.py
