name: Teams-AI-Notifier

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write
  actions: read

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      # 3️⃣ Build Application with Maven
      - name: Build Application with Maven
        id: build_app
        run: |
          set +e
          mvn clean package --batch-mode --no-transfer-progress > build_output.log 2>&1
          BUILD_STATUS=$?
          tail -n 50 build_output.log
          if [ $BUILD_STATUS -ne 0 ]; then
            tail -n 50 build_output.log | tr '\n' ' ' | sed 's/"/\\"/g' > error.log
          fi
          exit $BUILD_STATUS

      # 4️⃣ Prepare Error Log (for posting)
      - name: Prepare Error Log
        if: failure()
        run: |
          mkdir -p "${{ github.ref_name }}/${{ github.run_number }}"
          cp error.log "${{ github.ref_name }}/${{ github.run_number }}/error.log"

      # 5️⃣ Deploy Error Log to gh-pages (optional, for reference)
      - name: Deploy to gh-pages
        if: failure()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.ref_name }}
          keep_files: true

      # 6️⃣ Notify Teams via FastAPI
      - name: Notify Teams via FastAPI
        if: failure()
        run: |
          echo "Sending build failure info to FastAPI Teams service..."
          curl -X POST https://fastapi-teams-handler.onrender.com/notify \
          -H "Content-Type: application/json" \
          -d '{
            "repo": "${{ github.repository }}",
            "branch": "${{ github.ref_name }}",
            "actor": "${{ github.actor }}",
            "run_id": "${{ github.run_id }}",
            "run_number": "${{ github.run_number }}",
            "error_log": "$(cat error.log | jq -Rs .)"
          }'

      # 7️⃣ Ping FastAPI Service to keep alive (optional)
      - name: Ping Teams FastAPI Handler
        run: |
          echo "Pinging Teams FastAPI Handler..."
          curl --silent https://fastapi-teams-handler.onrender.com || true
